version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    env_file:
      - config/.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - botnet

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    networks:
      - botnet

networks:
  botnet:
